// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnobwirrspnrqjjehqsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdub2J3aXJyc3BucnFqamVocXNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDI3ODUsImV4cCI6MjA1OTc3ODc4NX0.bq4sJqhOvRCNkUFT4nfbj47LdUj_Po8tkgxmFmIqXew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);