
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://siglipzwvjohzjucxluu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpZ2xpcHp3dmpvaHpqdWN4bHV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjE5NTgsImV4cCI6MjA1OTQ5Nzk1OH0.LUhKjW2xgy-XNTJI_PBmF8hrYNBpk4bI6tX8E2suShU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
